### ISSUE TITLE
Failed to resolve: could not find `unix` in `os`

### ISSUE THREAD

**Issue by soywod** [staktrace/maildir#28]
It looks like the crate  does not compile on Windows: https://github.com/soywod/himalaya/runs/5290902164?check_suite_focus=true. The issue comes from `use std::os::unix::fs::MetadataExt;`, which is obviously not available on Windows. Why not using `std::fs::Metadata`?

**Comment by staktrace** [comment]
The code uses [things](https://github.com/staktrace/maildir/blob/dddfac8bb5fb2e1f13e3992762004686b42eafe9/src/lib.rs#L675-L676) that are in `MetadataExt` but not in `Metadata` due to the [uniqueness requirements](https://github.com/staktrace/maildir/blob/dddfac8bb5fb2e1f13e3992762004686b42eafe9/src/lib.rs#L632). That being said some of those could probably be skipped or replaced on windows with other parameters. I'd take a PR that added windows support using conditional compilation stuff.

**Comment by soywod** [comment]
I see. I will try to propose sth whenever I can. Thanks for you reply!

**Comment by soywod** [comment]
What do you think about replacing (only on windows):

- `dev` by [`volume_serial_number`](https://doc.rust-lang.org/stable/std/os/windows/fs/trait.MetadataExt.html#tymethod.volume_serial_number)
- `ino` by [`file_index`](https://doc.rust-lang.org/stable/std/os/windows/fs/trait.MetadataExt.html#tymethod.file_index)
- `size` by [`file_size`](https://doc.rust-lang.org/stable/std/os/windows/fs/trait.MetadataExt.html#tymethod.file_size)

**Comment by staktrace** [comment]
I'd like to avoid using nightly-only APIs. You can use the `file_size` one and just omit the other components. There's still enough to generate unique filenames.
